# -*- coding: utf-8 -*-
"""TechBoy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13s7Yl_F1jbKpQU4mk4iO5Ss--c-z70VT
"""

#TechBoy
def saudacao():
    print("E aí, galera! Tô chegando com aquela vibe de Bot descolado!")
def mostrar_menu():

    print('\n Qual é a boa na área da computação que tu tá querendo desvendar, tirar uma dúvida ou mergulhar de cabeça pra aprender mais?')
    print("\n Menuzão Tech pra Mandar Bem na Programação!\n")
    print("1. Intro às Linguagens de Programação - Pra tu começar a falar a língua dos códigos!")
    print("2. Lógica da Programação - Descola o jeito de pensar como um dev ninja!")
    print("3. Algoritmos - Cria as fórmulas mágicas que fazem tudo acontecer!")
    print("4. Variáveis - Domina as caixinhas que guardam os segredos do teu código!")
    print("5. Estruturas de Controle - Toma as rédeas e faz o código dançar no teu ritmo!")
    print("6. Funções - Libera o poder de criar teus próprios superpoderes no código!")
    print("7. Escolher uma Linguagem - Acha a tua vibe perfeita no mundo da programação!")
    print("0. Se quiser sair")

def introducao_programacao():
    print("""\n📘 Intro às Linguagens de Programação, bora lá!:
    Programação é tipo dar um tutorial pro computador, saca?
    É como se você fosse explicar, passo a passo, o que ele precisa fazer — desde somar 2+2 até criar o próximo app que vai bombar no TikTok. O computador é meio “literalzão”, então você usa uma linguagem de programação pra falar com ele.
    Cada linguagem tem sua personalidade e é boa pra algo específico, tipo escolher a playlist certa pra cada vibe.
    O que é linguagem de programação?
    Imagina que o computador é um gringo que só entende um idioma mega específico. A linguagem de programação é esse “idioma” que você usa pra conversar com ele. É um conjunto de regras e símbolos que transformam suas ideias em algo que a máquina entende. Tipo, se você quer criar um jogo, um site ou uma IA futurista, cada linguagem tem um jeitão que facilita pra cada tipo de projeto. Escolher a certa é como achar o filtro perfeito pro seu Insta.
    Definição de Linguagem de Programação
    Resumindo a real: linguagens de programação são como dicionários com regras pra você “falar” com o PC. Diferente de humanos, que entendem mesmo se você falar “duas caneta” em vez de “duas canetas”, o computador é super rígido. Cada linguagem é feita pra um tipo de rolê: uma é top pra apps, outra pra jogos, outra pra análise de dados. É como ter um dialeto pra cada situação da vida.
    Qual a linguagem de programação mais usada?
    As linguagens mais hypadas mudam com o tempo, mas pra saber quais tão bombando, a galera dev sempre dá uma olhada em rankings tipo o Índice TIOBE, StackOverflow, StackShare ou o GitHub Octoverse. É tipo checar o Spotify pra ver qual música tá no topo. Linguagens como Python, JavaScript e Java tão sempre na frente, mas a escolha depende do que você quer criar e do que a comunidade tá curtindo.
    Estruturas de diferentes linguagens de programação
    As linguagens são divididas em dois squads:
    Alto nível: São as mais “humanas”, tipo conversar com um amigo. Fáceis de escrever, ler e compartilhar. Ex.: Python, Java, JavaScript.
    Baixo nível: Mais próximas do papo da máquina (tipo código binário), são rápidas e eficientes, mas mais complicadas pra humanos.
    As de alto nível ainda têm subgrupos, dependendo do “estilo” de programação:
    Imperativas: Tipo dar ordens diretas.
    Orientadas a objetos: Organizam o código como “objetos” (pensa em Lego).
    Funcionais: Focam em funções matemáticas, tipo resolver equações.
    Lógicas: Baseadas em regras lógicas.
    Linguagens como C++, Java, Python e JavaScript são tipo “multitarefa” (multi-paradigma), porque misturam esses estilos. É como ser bom em dançar, cantar e atuar.""")

def logica_programacao():
    print("\n🧠 Lógica de programação:")
    print("""\n O que é lógica de programação?
	Imagina que você tá ensinando um robô superinteligente a fazer um café. Você precisa dar o passo a passo: pegar a xícara, colocar o pó, ligar a cafeteira... Isso é lógica de programação! É o jeito de organizar ideias e criar um conjunto de instruções (algoritmos) que o computador entende e executa. É tipo o cérebro por trás de tudo que rola nos apps, jogos e sites que a gente ama.
	O que precisa pra mandar bem?"
	Pra fazer o computador te obedecer (hehe), você precisa de uma linguagem de programação. É como o idioma que você usa pra conversar com a máquina. Tem várias opções no menu: Python (super versátil), JavaScript (o rei do front-end), C, Java, PHP... Cada uma tem seu rolê e brilha em diferentes projetos. Escolha a que mais combina com sua vibe e bora codar!
	Exemplos de códigos e algoritmos
	Tá na hora de ver a lógica ganhando vida! Vamos usar o clássico exemplo de calcular a média de três notas e dizer se o aluno passou ou não. Primeiro, em Python, porque é tipo o melhor amigo de quem tá começando:

	Python:
	# Calculando a média das notas
	# Pegando as notas
	nota1 = float(input("Joga a primeira nota aí: "))
	nota2 = float(input("Agora a segunda: "))
	nota3 = float(input("E a terceira, capricha: "))

	# Calculando a média
	media = (nota1 + nota2 + nota3) / 3

	# Verificando se passou (6 é o corte, bora torcer!)
	if media >= 6:
    print("Aprovado! Tô orgulhoso, parabéns! ")
	else:
    print("Reprovado... Mas vamo tentar de novo, tu consegue! ")

	# Mostrando a média com estilo
	print(f"A média foi: {media:.2f}")

	Agora, olha só como o mesmo algoritmo fica em JavaScript, pra quem curte aquele clima de web dev:

	JavaScript:
	// Calculando média com aquele toque de front-end
	let nota1 = parseFloat(prompt("Digita a primeira nota:"));
	let nota2 = parseFloat(prompt("Agora a segunda:"));
	let nota3 = parseFloat(prompt("E a terceira, vai com tudo:"));

	let media = (nota1 + nota2 + nota3) / 3;
	if (media >= 6) {
    console.log("Aprovado, tu arrasou!");
	} else {
    console.log("Reprovado, mas é só um perrengue, vamo melhorar!");
	}
	console.log(`Média: ${media.toFixed(2)}`);

	Viu? O algoritmo é o mesmo (pegar notas, calcular média, verificar aprovação), mas cada linguagem tem seu jeitinho de contar a história. A lógica é o coração, e a linguagem é só a ferramenta que você escolhe pra fazer o bagulho acontecer!
	Por que isso é tão f***?
	Lógica de programação é o superpoder que transforma ideias em realidade. Quer criar o próximo TikTok, um game insano ou um app que resolve a vida das pessoas? Tudo começa com um algoritmo bem bolado e uma linguagem que te dá aquele match perfeito. É o futuro, e você pode ser o protagonista dessa revolução tech!""")

def algoritmos():
    print("\n🔁 Algoritmos:")
    print("""\n Tipo, tudo que a gente faz no dia a dia tem uma vibe de passo a passo, sabe? É como se fosse uma coreografia que a gente dança sem nem perceber. Quer ver? Pensa em fazer um bolo delícia: tu pega os ingredientes, mistura tudo, joga na forma, leva pro forno e tcharam! Sai um bolo quentinho. 🍰 Cada um tem seu jeitinho de fazer, mas no fundo, é uma sequência lógica que te leva pro goal.
	Agora, quando o papo é programar, essa lógica vira o mood principal. Computadores não são como a gente, que entende no vibe. Eles precisam de um GPS bem certinho, tipo: 'faz isso, depois aquilo, e não pula nada!'. Essa sequência organizada é o que chamamos de lógica de programação, e o mapinha pra chegar lá é o algoritmo. É tipo o tutorial perfeito pra qualquer missão!
	O que é um algoritmo, afinal?
	É basicamente uma lista de passos pra alcançar um objetivo. Pode ser desde atravessar a rua, fazer um bolo ou decidir se um aluno passou de ano. É o hack pra resolver problemas de boa!
	Como criar um algoritmo?
	Antes de sair codando, tu precisa planejar direitinho: o que precisa ser feito? Como? É tipo montar um moodboard antes de criar algo. Aí tu escreve o passo a passo, testa pra ver se funciona e só depois escolhe a linguagem de programação pra dar vida ao teu plano.
	Como representar um algoritmo?
	Tem várias formas de botar isso no papel (ou na tela):")
	• Narrativa: tu escreve a sequência como se fosse uma história. Exemplo: calcular a média de um aluno. Pega as notas de 3 bimestres, soma, divide por 3, e vê se é maior ou igual a 7. Aprovado? Reprovado? Simples!
	• Fluxograma: é tipo um mapa visual, com setinhas e caixinhas, bem aesthetic.
	• Pseudo-código: aqui tu escreve em português, mas já com uma carinha de código, sem ser super rígido.
	Olha só: Pseudo-código
	Algoritmo CalcularMedia
	Ler Nota1, Nota2, Nota3
	Media = (Nota1 + Nota2 + Nota3) / 3
	Se Media >= 7 então
	Print "Aprovado, parabéns!"
	Senão
		Print "Reprovado, vamo tentar de novo? "
		Print "Sua média foi: ", Media
	Fim

	Resumindo a vibe: Algoritmos são tipo playlists de passos que guiam a gente (ou o PC) até o resultado. É planejar, organizar e executar com aquele toque de criatividade. Bora dominar essa lógica e criar coisas incríveis?")
	print("Exemplo: para fazer um café, você segue passos como aquecer a água, colocar o pó, coar, etc.""")

def variaveis():
    print("\n📦 Variáveis:")
    print("""\n Guia das Variáveis: A Caixinha Mágica da Programação!")
	Imagina uma variável como uma caixinha estilosa na memória do teu PC ou celular, tipo um baú mágico que guarda coisas iradas: pode ser um número, um textão, uma vibe verdadeira ou falsa, ou até uns dados mais complexos que são tipo o próximo nível do game. O nome 'variável' já entrega: ela é flex, mutável, pode trocar de conteúdo quando tu quiser, saca?
	Desenrolando a ideia:
	• Guarda as paradas: Variáveis são tipo o HD do teu programa, salvando tudo que tu precisa pra fazer a mágica acontecer.
	• Codinome maneiro: Cada variável tem um nome pra tu chamar ela, tipo um apelido que te leva direto pro que tá guardado.
	• Vários sabores: Elas seguram todo tipo de dado – números inteiros, números com vírgula, frases, emojis, true or false, e até uns objetos que são tipo naves espaciais de dados.
	• Troca de figurinha: O que tá na variável pode mudar no meio do rolê. Tipo, começou com um valor e, de repente, é outro, sem drama.
	• Exemplo na real: Quer guardar o nome de alguém? Cria uma variável chamada 'nome' e joga 'João' lá. Depois, se quiser, troca pra 'Maria' e tá de boa.
	Tipos de variáveis:
	As variáveis podem ser de vários tipos, dependendo do que você quer guardar:
	• Inteiros: números inteiros (ex.: 10, -5)
	• Flutuantes: números com casas decimais (ex.: 3.14, -0.5)
	• Strings: textos (ex.: 'Olá, mundo!')
	• Booleanos: verdadeiro ou falso (ex.: True ou False)
	Resumindo a treta: Variável é aquele espacinho na memória que segura um valor pra teu programa usar, remexer ou dar um confere.""")
    print("Exemplo em Python: idade = 25")

def estruturas_controle():
    print("\n🧩 Estruturas de controle:")
    print("""\n Estruturas de Controle: O GPS do Código!
  Imagina que você tá dirigindo e precisa decidir se vira à esquerda ou à direita. As estruturas de controle são tipo o GPS do teu código, ajudando a tomar decisões e seguir caminhos diferentes dependendo do que rola. Elas são essenciais pra fazer o programa funcionar direitinho, sem ficar perdido no meio do caminho.
	O que são estruturas de controle?

	São comandos que ajudam a controlar o fluxo do programa, decidindo quais partes do código vão ser executadas dependendo de certas condições ou repetições.

	Resumo com vibe visionária:
	Imagina um app bancário que não só gerencia teu dinheiro, mas te dá aquele empowerment pra tomar decisões financeiras com confiança. Pra isso, precisamos de lógica condicional: se o saldo da conta for suficiente, o saque rola de boa; se não, o app te avisa com jeitinho, tipo 'ops, saldo tá de boa, mas não pra esse saque'. Em Python, usamos if e else pra fazer isso acontecer, com uma sintaxe clean que deixa tudo mais intuitivo. Além disso, podemos brincar com condições mais complexas usando operadores como and e or, criando regras que são tipo o GPS das nossas decisões no código. O futuro? É um código que não só funciona, mas conversa com o usuário e torna a experiência fluida e humana.
	Plano pro código
	1. Pegar o exemplo do C# e passar pra Python, mantendo a lógica de verificar o saldo antes do saque.
	2. Substituir MessageBox.Show por print, já que Python é mais sobre console ou interfaces custom.
	3. Traduzir os operadores lógicos (&& vira and, || vira or) e simplificar a sintaxe.
	4. Adicionar um toque de modernidade com mensagens mais descontraídas.
	5. Mostrar como usar variáveis booleanas pra deixar o código mais legível e reutilizável.

	Exemplo em Python:
	saldo = 100.0
	valor_saque = 10.0

	# Verifica se o saque é possível e se o valor é positivo
	pode_sacar = (saldo >= valor_saque) and (valor_saque > 0)

    if pode_sacar:
      saldo -= valor_saque
	print("Saque no capricho! Novo saldo:", saldo)
    else:
	print("Ops, saldo tá meio tímido pra esse saque!")

	Como usar e por que é tudo
	Esse código é tipo um mood: simples, direto e com uma vibe que conecta. Você pode rodar ele no seu editor Python favorito (tipo VS Code ou PyCharm) ou até num Jupyter Notebook pra testar rapidinho. A variável pode_sacar é um bool que mistura duas condições com and, garantindo que o saque só rola se o saldo for suficiente e o valor do saque for maior que zero. Isso é tipo ter um filtro de segurança que deixa teu app mais confiável.""")
    print("/Exemplos: if/else para condições, while/for para repetições.")

def funcoes():
    print("\n🛠️ Funções:")
    print("""\nO que são funções?
	Funções são blocos de código que realizam uma tarefa específica. Elas podem receber dados (parâmetros), processá-los e devolver um resultado (retorno). É como ter uma caixa mágica que transforma ingredientes em um prato delicioso!
	Como criar uma função?
	Pra criar uma função, você precisa definir o nome dela, os parâmetros (se houver) e o que ela vai fazer. Depois, é só chamar a função quando precisar. É tipo ter um botão mágico que ativa o superpoder sempre que você quiser!
	Exemplo de função em Python:
	def calcular_media(nota1, nota2, nota3):
	media = (nota1 + nota2 + nota3) / 3
		return media
	# Chamando a função
	media_aluno = calcular_media(7, 8, 9)
	print("A média do aluno é:", media_aluno)
	Nesse exemplo, a função calcular_media recebe três notas, calcula a média e devolve o resultado. Você pode chamar essa função quantas vezes quiser, com notas diferentes, e sempre vai ter a média na mão!
	Por que usar funções?
	Funções ajudam a deixar o código mais organizado e fácil de entender. Elas evitam repetições desnecessárias e permitem que você reutilize o mesmo código em diferentes partes do programa. Além disso, se precisar fazer uma mudança, é só atualizar a função e pronto! É como ter um assistente pessoal que cuida de tudo pra você.

	Funções são o superpoder do código! Elas ajudam a organizar, reutilizar e tornar tudo mais legível. Então, bora usar essa magia na programação e criar coisas incríveis juntos!""")

def linguagens_existentes():
    print("\n🌐 Linguagens de programação existentes:")
    print("Python: Fácil e popular, versátil e conhecida pela sua facilidade de uso e ampla aplicação em diversas áreas, incluindo ciência de dados, desenvolvimento web, automação e inteligência artificial.")
    print("   - Documentação oficial: https://docs.python.org/3/")
    print("   - Curso gratuito: https://www.cursoemvideo.com/course/python-3-mundo-1/")

    print("JavaScript: Popular e fácil de aprender, amplamente utilizada em desenvolvimento web para adicionar interatividade e dinamismo aos sites. Além do desenvolvimento web, JavaScript também é usado em diversas outras áreas, como automação de tarefas e criação de aplicativos.")
    print("   - Documentação oficial: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript")
    print("   - Curso gratuito: https://www.cursoemvideo.com/course/javascript/")

    print("Java: É uma linguagem de programação amplamente utilizada, reconhecida pela sua popularidade no mercado de trabalho e em diversas áreas de desenvolvimento. Embora possa ser considerada mais complexa para iniciantes, a sua versatilidade e presença em projetos web, aplicativos Android e outras aplicações a tornam uma linguagem essencial.")
    print("   - Documentação oficial: https://docs.oracle.com/en/java/")
    print("   - Curso gratuito: https://www.cursoemvideo.com/course/java-basico/")

    print("C++: É uma versão ampliada e modificada do C, que inclui orientação a objetos e outros recursos adicionais. É amplamente utilizada em jogos, sistemas de baixo nível.")
    print("   - Documentação: https://en.cppreference.com/w/")
    print("   - Curso introdutório: https://www.youtube.com/watch?v=cmFvLJPJbC4")

    print("Outras: C#, Ruby, Go, Swift, PHP, etc.")
    print("   - Visão geral: https://roadmap.sh/")


# Execução do TechBoy
saudacao()
nome = (input("Qual é o teu primeiro nome? ")).capitalize()
print(f"Eae, {nome}!")
while True:
    mostrar_menu()
    try:
        escolha = int(input("\nDigite o número da opção que tu tá querendo matar a curiosidade: "))

        if escolha == 1:
            introducao_programacao()
        elif escolha == 2:
            logica_programacao()
        elif escolha == 3:
            algoritmos()
        elif escolha == 4:
            variaveis()
        elif escolha == 5:
            estruturas_controle()
        elif escolha == 6:
            funcoes()
        elif escolha == 7:
            linguagens_existentes()
        elif escolha == 0:
            print("\n👋 Massa que você usou o TechBot! Nos vemos na próxima, valeu? Se precisar de mais ajuda, é só chamar.")
            break
        else:
            print("\n⚠️ Ops, essa opção não rola. Tenta um número do menu, vai!")
    except ValueError:
        print("\n🚫 Calma, só números inteiros, tá? Nada de letras ou emojis aqui! Você consegue, confia!")